name: C++ Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: build
          key: cmake-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ make

      - name: Configure CMake (Debug + Tests)
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON

      - name: Build project
        run: |
          cmake --build build --parallel

      - name: Run Google Tests
        run: |
          cd build
          ctest --output-on-failure
      
      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: "Automated release from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Upload Release Assets
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: build/AteNika
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
